FROM jenkins/jenkins:lts

USER root

RUN apt-get update
RUN apt-get install \
    apt-transport-https \
    ca-certificates \
    curl \
    gnupg2 \
    software-properties-common -y
RUN curl -fsSL https://download.docker.com/linux/debian/gpg | apt-key add -
RUN add-apt-repository \
   "deb [arch=amd64] https://download.docker.com/linux/debian \
   $(lsb_release -cs) \
   stable"
RUN apt-get update
RUN apt-get install docker-ce-cli -y
RUN chmod +x /usr/bin/docker  && \
    groupadd -g 999 docker && \
    usermod -a -G docker jenkins
    
USER jenkins